### ISSUE TITLE
How do I fix this so I can make a Server?

### ISSUE THREAD

**Issue by 00Mythic00** [DarkPacks/SevTech-Ages#1081]
Installing server to current directory
MESSAGE: Considering minecraft server jar
MESSAGE: Downloading minecraft server version 1.12.2
java.net.UnknownHostException: s3.amazonaws.com
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:457)
	at net.minecraftforge.installer.DownloadUtils$URLISSupplier.getInput(DownloadUtils.java:445)
	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)
	at com.google.common.io.Files.copy(Files.java:382)
	at net.minecraftforge.installer.DownloadUtils.downloadFileEtag(DownloadUtils.java:174)
	at net.minecraftforge.installer.ServerInstall.run(ServerInstall.java:53)
	at net.minecraftforge.installer.InstallerAction.run(InstallerAction.java:43)
	at net.minecraftforge.installer.SimpleInstaller.handleOptions(SimpleInstaller.java:72)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:47)
Caused by: java.net.UnknownHostException: s3.amazonaws.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.PlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(Unknown Source)
	at net.minecraftforge.installer.DownloadUtils.downloadFileEtag(DownloadUtils.java:163)
	... 4 more
Downloading minecraft server failed, invalid e-tag checksum.
Try again, or manually place server jar to skip download.
There was an error during server installation
 
I don't know what to do with this.

**Comment by sarcastic6** [comment]
`java.net.UnknownHostException: s3.amazonaws.com`

Looks like a DNS problem.  Certainly not a pack problem!

**Comment by artdude543** [comment]
DNS Issue as stated and not a pack issue. Closing.
