### ISSUE TITLE
Game freezes when entering a planet in galactic craft (moon)

### ISSUE THREAD

**Issue by BananaLord12** [DarkPacks/SevTech-Ages#1695]
## Issue / Bug
I have been having some issues with galactic craft when i visit a planet, right at the end of age 4 i went to the moon, but my game was frozen in the loading screen upon entering the planet and the only way to fix it is to relaunch the pack. Unfortunately, it takes ages to load the pack....

## Steps to Reproduce (for bugs)

1. Make Fuel
2. Make the tier 1 rocker and the launch pad
3. Place launch pad and place tier 1 rocket
4. launch the rocket with fuel
5. Visit the moon

## Logs
* Client/Server Log: https://pastebin.com/bn2wGsqF - This is the end of the log since the log file is really long and dont want to make multiple version, but at the bottom i am leaving the planet and i had to relaunch the pack.

## Client Information
* Modpack Version: 3.0.6
* Java Version: Latest
* Launcher Used: Twitch
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: 1.12.2_HD_U_C9

## Server Information
* Java Version: 1.8.0_74
* Operating System: Linux
* Hoster/Hosting Soultion:  Dedicated Server from OVH
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?:

**Comment by MJRLegends** [comment]
Looks to be a error from the carry on mod

```
java.lang.NullPointerException: null
    at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:224) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
    at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:?]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
    at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) [SimpleNetworkWrapper.class:?]
    at tschipp.carryon.common.item.ItemTile.func_180614_a(ItemTile.java:156) [ItemTile.class:?]
```

**Comment by BananaLord12** [comment]
How would that affect the game freezes on the loading screen upon entering a planet?

**Comment by MJRLegends** [comment]
Because code is running in the background even if that mod isnt being used there is still events being triggered and ticked as the game/player does things

**Comment by justinrusso** [comment]
@BananaLord12 Has this issue continued to happen or all seems to be good? It appears like no one else has been having this issue.
