### ISSUE TITLE
Server crashes: Exception ticking world

### ISSUE THREAD

**Issue by JIrgend** [DarkPacks/SevTech-Ages#2512]
## Issue
Server and SP Crashes, server crashed suddenly with no warning. 

## Context
Just reaches age 4, we wanted to automate the immersive engineering coke oven with Buildcraft pipes (fluid and item) and Hopping Bonsai pot, then it crashed. 

## Logs
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  CorePlugin (SmoothFont-1.12.2-1.14.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.170.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.6-core.jar)
  LoadingPlugin (noRecipeBook_v1.1.0formc1.12.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.6-1.12.2-anarchy.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  BNBGamingCore (BNBGamingCore-1.12-0.7.1.jar)
  FarseekCoreMod (Farseek-1.12-2.2.5.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 5/17/18 10:25 PM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:114)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:114)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['jirgend'/1247884, l='world', x=655.51, y=71.00, z=-723.31], EntityPlayerMP['Skelten'/1426575, l='world', x=648.26, y=71.00, z=-724.45]]
	Chunk stats: ServerChunkCache: 537 Drop: 0
	Level seed: -3062429506297371672
	Level generator: ID 06 - quark_realistic, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (626,67,-744), Chunk: (at 2,4,8 in 39,-47; contains blocks 624,0,-752 to 639,255,-737), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 10595960 game time, 2795027 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 28823 (now: false), thunder time: 97845 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

## Server Information
* Java Version: 1.8.0_171
* Operating System: Debian Linux (amd64) version 4.9.0-6-amd64
* Hoster/Hosting Soultion: selfhost
* Sponge (Non-Vanilla Forge) Server?: no
*Memory: 970878280 bytes (925 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)

**Comment by justinrusso** [comment]
What version of the pack are you running?

**Comment by JIrgend** [comment]
sure, thank you for the quick response. I will try it afap
