### ISSUE TITLE
Sevtech ages 3.0.8: Crashing to desktop

### ISSUE THREAD

**Issue by CtrlAltDavid01** [DarkPacks/SevTech-Ages#2956]
## Bug Report

Me and my friend played on a server that I ran and today, when I tried to join it crashed to desktop, reporting the following error:
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float

We played about 50 hours, so we really don't want to loos our progress.

Server:
[13:20:51] [Netty Server IO #13/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: A létező kapcsolatot a távoli állomás kényszerítetten bezárta
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_172]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_172]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_172]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_172]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_172]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]

## Expected Behaviour

Should be abel to play without crashing!
## Logs

* Client/Server Log:
* Crash Log:
Client crash log: https://pastebin.com/HJtWvMZH
I can Include a server log, if it's needed, but thats over 3 megabytes, so I can't upload it to pastebin.

## Client Information

* Modpack Version: 3.0.8
* Java Version: Java 8 162 and 172
* Launcher Used: Twitch
* Memory Allocated: 12 GB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information

* Modpack Version world created in:

* Additional Content Installed:
Optifine

## Server Information
* Java Version: Java 8 162
* Operating System: Windows 10 1803 64 bit
* Hoster/Hosting Solution: My computer
* Sponge (Non-Vanilla Forge) Server: No

**Comment by artdude543** [comment]
This was fixed in the mod update in 3.0.8 and is a rare case. The world should load back up fine when you try again. If not you can enable in the `forge.cfg` to delete ticking entities. _Note: This can delete other stuff also_
