### ISSUE TITLE
Tinker's Steel Sharpness Effect Conflicting With Something; Corrupts Playerdata

### ISSUE THREAD

**Issue by ChaoticNonsense** [DarkPacks/SevTech-Ages#2963]
## Bug Report

Hitting a player with a Tinker's weapon with a steel component can kick them from server, and they cannot relog until their playerdata is edited. I've triggered the error 100% of the time since discovering it, even when hitting myself. This never occurred before adding the steel component. Given the nature of the error log, ("Modifier is already applied on this attribute!") it is most likely caused by a conflict between different effects. This hypothesis is further supported by the following: 1) the offending weapon was a shuriken with 4 different parts/effects (details in steps to reproduce below), 2) physically whacking a player with a steel bow caused the bleeding without the corruption. 

## Expected Behaviour

Player data not being corrupted.

## Possible Solution

The temporary fix was to delete all "Active effect" entries in the player's nbt file. The player could log in just fine after that.

## Steps to Reproduce (for bugs)

1. Make the following Shuriken: Steel, bone, steelleaf, fiery
2. Hit a player with it.
Note: This was tested on two different players. The only common effects between both of us were the buffs from having full nutrition in all categories. So the problem is either the weapon alone, or the weapon conflicting with the nutrition buffs.

## Logs

* Client/Server Log:

On hit, the following message is thrown several times before kicking the player with an "Internal Server Error":

[05:18:42] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /104.159.161.36:62505
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
**Caused by: java.lang.IllegalArgumentException: Modifier is already applied on this attribute!**
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:89) ~[wh.class:?]
	at slimeknights.tconstruct.library.modifiers.Modifier.attackEntitySecondary(Modifier.java:280) ~[Modifier.class:?]
	at slimeknights.tconstruct.library.modifiers.Modifier.attackEntitySecondary(Modifier.java:266) ~[Modifier.class:?]
	**at slimeknights.tconstruct.tools.traits.TraitSharp.dealDamage(TraitSharp.java:43) ~[TraitSharp.class:?]**
	**at slimeknights.tconstruct.tools.traits.TraitSharp$DoT.func_76394_a(TraitSharp.java:62) ~[TraitSharp$DoT.class:?]**
	at net.minecraft.potion.PotionEffect.func_76457_b(PotionEffect.java:132) ~[va.class:?]
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:114) ~[va.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:605) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:351) ~[vp.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
* Crash Log: N/A

## Client Information

Note: Bug is entirely server-side.

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171 64 Bit
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: GottaGoFast

## Server Information
* Java Version: Unknown
* Operating System: Unknown
* Hoster/Hosting Solution: Akliz.net
* Sponge (Non-Vanilla Forge) Server:

**Comment by agilmore2** [comment]
I just experienced this in Sevtech Ages latest release, 3.0.8.
`[22:29:10] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /<IP>:49676
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:89) ~[wh.class:?]
	at slimeknights.tconstruct.library.modifiers.Modifier.attackEntitySecondary(Modifier.java:280) ~[Modifier.class:?]
	at slimeknights.tconstruct.library.modifiers.Modifier.attackEntitySecondary(Modifier.java:266) ~[Modifier.class:?]
	at slimeknights.tconstruct.tools.traits.TraitSharp.dealDamage(TraitSharp.java:43) ~[TraitSharp.class:?]
	at slimeknights.tconstruct.tools.traits.TraitSharp$DoT.func_76394_a(TraitSharp.java:62) ~[TraitSharp$DoT.class:?]
	at net.minecraft.potion.PotionEffect.func_76457_b(PotionEffect.java:132) ~[va.class:?]
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:114) ~[va.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:605) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:351) ~[vp.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
`
