### ISSUE TITLE
3.0.8 Linux Server, Frozen Solid, Offline recovery

### ISSUE THREAD

**Issue by pocketpacket** [DarkPacks/SevTech-Ages#2966]
## Bug Report

3.0.8 Linux server instance frozen rock solid

Came home from work to find the server instance completely
frozen, tried to do partial restore and the server continued
to die. A full daily *offline rollback was require to restore the 
server and I yet, have no idea what caused it to freeze rock solid.
Debug log is too large to upload, i'll post the latest.log before
the freeze. Last person on was in Twilight forest, large spike -
 20k spike then frozen

Locked up solid, I was not even able to kill the pid to recover
the instance, force server restart was required, other server
instances seemed to be ok, shut them down before sudo reboot

not do the above

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: latest.log server, debug too big
* Crash Log:

https://gist.github.com/pocketpacket/de073886f481e015080d8f3564e4bd0a

## Client Information

* Modpack Version: 3.0.8
* Java Version: unknown
* Launcher Used: unknown
* Memory Allocated: unknown
* Server/LAN/Single Player: server, internet
* Optifine Installed: no idea
* Shaders Enabled: no idea

## World Information

* Modpack Version world created in: 
3.0.7 May 11th 2018

* Additional Content Installed: 
Just what came in pack

## Server Information Xeon 3.9 ghz 128 ECC, Raid 6
* Java Version: 8.171 - 16 - 24 gig dedicated
* Operating System: Ubuntu 18.04
* Hoster/Hosting Solution: me
* Sponge (Non-Vanilla Forge) Server: Your Server Download

**Comment by Tahakk** [comment]
Latelly I noticed that sometimes when player disconnects this code will start spilling out full speed:

`
[Netty Server IO #0/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
`

full log that I found can be found [here](http://triiish.com/#files%2Fmc_logs) - both errors start around 10,3k - 11,5k

check if you have it the same, otherwise I will open new issue with this

**Comment by pocketpacket** [comment]
No, i have a seperate issue with logs about the disconnections, this was
a flat out frozen server. I did not see any disconnection issues in 3.0.7
but other then the constant jm_dim_permission spamming and massive
leakage in the debug logs. 1 person was playing in the twilight forest it
seems then 20k spike and everything locked up solid. The other server
instances ran normally, but a full sudo reboot was require to recover
the instance and full server recovery offline rollback. 

besides.

io.netty.channel.unix.Errors$NativeIoException: syscall:writev(..) failed: Broken pipe
	at io.netty.channel.unix.FileDescriptor.writeAddresses(..)(Unknown Source) ~[minecraft_server.1.12.2.jar:?]
[15:27:58] [Netty Epoll Server IO #7/ERROR] [FML]: NetworkDispatcher exception
io.netty.channel.unix.Errors$NativeIoException: syscall:writev(..) failed: Broken pipe
	at io.netty.channel.unix.FileDescriptor.writeAddresses(..)(Unknown Source) ~[minecraft_server.1.12.2.jar:?]
[15:27:58] [Netty Epoll Server IO #7/ERROR] [FML]: NetworkDispatcher exception
io.netty.channel.unix.Errors$NativeIoException: syscall:writev(..) failed: Broken pipe
	at io.netty.channel.unix.FileDescriptor.writeAddresses(..)(Unknown Source) ~[minecraft_server.1.12.2.jar:?]
[15:27:58] [Netty Epoll Server IO #7/ERROR] [FML]: NetworkDispatcher exception
