### ISSUE TITLE
Problem when i start the minecraft server

### ISSUE THREAD

**Issue by zRoCkyIT** [DarkPacks/SevTech-Ages#2990]
`A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge                                           tException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                      java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                           sorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunc                                           hWrapper.java:62)
    at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaun                                           chWrapper.java:31)`
`Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    ... 6 more`
`Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 8 more`

**Comment by Stifling-Bossness** [comment]
Please follow the template provided or your will issue will not receive support.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
