### ISSUE TITLE
Cant load the game?

### ISSUE THREAD

**Issue by godlyberries** [DarkPacks/SevTech-Ages#3016]
Hi there! I just downloaded the mod after seeing some pretty cool play throughs, but I can't get the game to load. Every time I press play on the launcher I get this error message: 

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Does anyone know what this means and how can I fix it?

**Comment by godlyberries** [comment]
Hi there Kieron!

Sorry for the late reply, it has been a busy work week. I wasn't sure if my
problem fit the template/ didn't understand a lot of the template so I am
sorry for the confusion I caused! I will try again more thoroughly this
time, and look up terms as needed.

Thank you for your patience and time,

Sarah
