### ISSUE TITLE
I can't start up the modpack

### ISSUE THREAD

**Issue by AllegoricSiren** [DarkPacks/SevTech-Ages#3042]
## Bug Report
I go to twitch, I install, and then I click play. it opens up the 1.11 browser and I click play. it starts to load then I get an error message.

## Expected Behaviour
It just doesn't start instead of loading up

## Possible Solution
Reinstalling modpack (did that)
reinstalling Minecraft 
not sure what else
## Steps to Reproduce (for bugs)
1.Open twitch
2.dowload modpack
3.(I don't think I was using at the time but) Download and try to install server version of modpack
4.install server forge
5.install regular forge after giving up on trying to set up server
6.click play on twitch (Somehow 3 profiles were made idk why)
7.minecraft loads and hit play
8.runinto issue and go to GitHub 

## Logs
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I don't think it creates a crash report, only this.
## Client Information
Kind of cluttered rn since I was experimenting with adding mods to servers (I have no idea what I'm doing) I tried to use this modpack multiple times but kept getting errors and such and reinstalled a couple of forges but the most recent one I did was not for servers. I've had other mods (Not server or twitch mods) On my Minecraft before this.
* Modpack Version:3.0.8
* Java Version: most resent. I tried to install java 8 to be sure and it said I had a newer Java.
* Launcher Used:1.6.91
* Memory Allocated: Not sure but probably a lot
* Server/LAN/Single Player: I think single player but idk. I tried to set up a server but it kept running into errors so I tried to go to single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: No world created

* Additional Content Installed: Nothing atm

**Comment by AllegoricSiren** [comment]
Actually, wait. My game loads on the 1.6.91 launcher, but I see everyone else opening it in the most recent launcher. Why is mine opening in the old launcher?

**Comment by AllegoricSiren** [comment]
I eventually gave up doing it through twitch and did it all manually. its working fine <3
