### ISSUE TITLE
Sevtech crashes on loading textures every time without fail

### ISSUE THREAD

**Issue by AllegoricSiren** [DarkPacks/SevTech-Ages#3145]
## Bug Report
On load, everything is running as normal and loading but once I get to stage 3 it always crashes

## Expected Behaviour
Expected behavior - Load up Sevtech modpack from twitch and the game loads perfectly fine
Actual behavior - Sevtech starts loading up but crashes after a while of loading textures
## Possible Solution
Allocate more ram using the slider on twitch in the settings (done)
use a different profile (done)
remove the mod that is said to me the cause of the crash (don't but I still crashed form a different mod)
Allocate more ram through your computer (idk how)

## Steps to Reproduce (for bugs)
1.open twitch
2.click settings
3. minecraft
4. turn maximum memory allocation to the max
5. start loading modpack
6. runs like normal
7. gets to texture sticking section and stitches the first batch of textures but once it gets to the second it crashes

## Logs
Description: Initializing game

net.minecraft.client.renderer.StitcherException: Unable to fit: pneumaticcraft:items/sentry_turret_item - size: 32x32 - Maybe try a lowerresolution resourcepack?
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:70)
	at net.minecraft.client.renderer.texture.TextureMap.finishLoading(TextureMap.java:213)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:112)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:70)
	at net.minecraft.client.renderer.texture.TextureMap.finishLoading(TextureMap.java:213)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:112)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

## Client Information

* Modpack Version: latest
* Java Version: 1.8.0.171 64 bit
* Launcher Used: jar
* Memory Allocated: 12,288MB
* Server/LAN/Single Player:Single player
* Optifine Installed:no
* Shaders Enabled:no

## World Information
N/A

EXTRA INFO-
Using NO TEXTUREPACK
I am on a Mac, its updated to the latest version of Mac.
I've tried so many things and I just want to play this pack : - : I even tried to get help on the discord but no one could help. I can't believe that there isn't SOMETHING I can do

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
