### ISSUE TITLE
3.0.8 Server Crash on joining - Netty Server IO Error

### ISSUE THREAD

**Issue by BeNikPlays** [DarkPacks/SevTech-Ages#3317]
## Bug Report
[13:00:12] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
        at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_181]
        at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_181]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_181]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_181]
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[13:00:12] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
        at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_181]
        at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_181]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_181]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_181]
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[13:00:12] [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen

**This is in a loop. It stops after a while.
This comes only on one of three clients.**

## Logs
There is no log for this.

## Client Information
* Modpack Version: 3.0.8
* Java Version: 8 (181)
* Launcher Used: From the Server files.
* Memory Allocated: 10G
* Server/LAN/Single Player: LAN
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 8 (181)
* Operating System: Windows 10

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.
