### ISSUE TITLE
100% CPU Load

### ISSUE THREAD

**Issue by magoo89** [DarkPacks/SevTech-Ages#3445]
**We have a Sevtech Ages Server and after maybe 12 hours the server startet 100% CPU Load. After a Reboot it doesent go away. the last step on the logfiles are always**

```
[03:22:22] [Aromabackup-Backup/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [§1AromaBackup§r] Server Backup done!§r
[03:22:22] [Aromabackup-Backup/INFO] [AromaBackup]: Releasing server Thread.
[09:25:04] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2002ms behind, skipping 40 tick(s)
[09:25:32] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2321ms behind, skipping 46 tick(s)
[09:28:33] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2396ms behind, skipping 47 tick(s)
[
.
.
.
.
.

```

**now when i type the command in the minecraft console: /backup**

```
[14:24:49] [Server thread/INFO] [Astral Sorcery]: [AstralSorcery] Loading of 'lightnetwork' for world 0 finished.
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension 28885
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension 10
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension 7
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension 53
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension 144
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension 52
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension 51
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension -1
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension 50
[14:24:50] [Server thread/INFO] [FML]: Unloading dimension 1
[14:24:50] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2085ms behind, skipping 41 tick(s)
[14:24:55] [Server thread/INFO] [weirdinggadget]: All players have gone offline. Ticket is scheduled to expire at world time 109486175
[14:24:55] [Server thread/INFO] [weirdinggadget]: All players have gone offline. Ticket is scheduled to expire at world time 109486175
[14:24:55] [Server thread/INFO] [weirdinggadget]: All players have gone offline. Ticket is scheduled to expire at world time 109486175
[14:24:55] [Server thread/INFO] [weirdinggadget]: All players have gone offline. Ticket is scheduled to expire at world time 109486175
[14:25:14] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 9158ms behind, skipping 183 tick(s)
> /backup
[14:25:14] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [AromaBackup] Server started a backup.
> [14:25:14] [Aromabackup-Backup/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [AromaBackup] Starting Backup. The server may lag for a bit!
[14:25:16] [Aromabackup-Backup/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchFieldError: SERVER
[14:25:16] [Aromabackup-Backup/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at aroma1997.backup.mc.ThreadBackup.executeOnServerThreadAndWait(ThreadBackup.java:283)
[14:25:16] [Aromabackup-Backup/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at aroma1997.backup.mc.ThreadBackup.makeBackup(ThreadBackup.java:126)
[14:25:16] [Aromabackup-Backup/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at aroma1997.backup.mc.ThreadBackup.run(ThreadBackup.java:102)
[14:25:16] [Aromabackup-Backup/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:  at java.lang.Thread.run(Thread.java:748)
```
**When i delete the mod AromaBackup-1.12.2-2.1.1.4.jar Everything is okay.**

We have the newest version of the modpack and a fresh Debian 9 installation with newest Java version.

openjdk version "1.8.0_181"

CPU 7700K
RAM 64gb
greetz **magoo**

**Comment by Tahakk** [comment]
Well there you go, it was doing backup. What more do you need to know.

**Comment by magoo89** [comment]
i have nonstop 100% cpu load when it makes a few times backups.
