### ISSUE TITLE
Server Exception Handling - Reoccurring Error

### ISSUE THREAD

**Issue by Otisdahousekats** [DarkPacks/SevTech-Ages#3573]
Every time I launch the server I get the following errors.

[INFO] [Mekanism]: Mod loaded.

[WARNING] [FML]: No types have been added to Biome appliedenergistics2:storage_biome, types have been assigned on a best-effort guess: [COLD, PLAINS]

[WARNING] [FML]: No types have been added to Biome nex:hell, types have been assigned on a best-effort guess: [HOT, PLAINS, SAVANNA, DRY]

[WARNING] [FML]: No types have been added to Biome nex:ruthless_sands, types have been assigned on a best-effort guess: [HOT, PLAINS, SAVANNA, DRY]

[WARNING] [FML]: No types have been added to Biome nex:fungi_forest, types have been assigned on a best-effort guess: [HOT, PLAINS, SAVANNA, DRY]

[WARNING] [FML]: No types have been added to Biome nex:torrid_wasteland, types have been assigned on a best-effort guess: [HOT, PLAINS, SAVANNA, DRY]

[WARNING] [FML]: No types have been added to Biome nex:arctic_abyss, types have been assigned on a best-effort guess: [COLD, PLAINS, DRY]

[Server thread/DEBUG] [BnBGamingCore]: Caught Exception while attempting to get class extensions for betterwithmods.module.Module$$Lambda$2546.00000000A7C8A450

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better With Mods (betterwithmods)

Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: Class 'betterwithmods.module.tweaks.MineshaftGeneration' no access to: class 'net.minecraft.world.gen.structure.StructureMineshaftPieces$Peice'

at betterwithmods.module.tweaks.MineshaftGeneration.init(MineshaftGeneration.java:55) ~[MineshaftGeneration.class:?]

at betterwithmods.module.Module.lambda$init$3(Module.java:150) ~[Module.class:?]

at betterwithmods.module.Module$$Lambda$2546.00000000A7C8A450.accept(Unknown Source) ~[?:?]

at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_192]

at betterwithmods.module.Module.forEachEnabled(Module.java:212) ~[Module.class:?]

at betterwithmods.module.Module.init(Module.java:150) ~[Module.class:?]

at betterwithmods.module.ModuleLoader.lambda$init$3(ModuleLoader.java:80) ~[ModuleLoader.class:?]

at betterwithmods.module.ModuleLoader$$Lambda$2545.00000000A7C8A000.accept(Unknown Source) ~[?:?]

at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_192]

at betterwithmods.module.ModuleLoader.forEachEnabled(ModuleLoader.java:200) ~[ModuleLoader.class:?]

at betterwithmods.module.ModuleLoader.init(ModuleLoader.java:80) ~[ModuleLoader.class:?]

at betterwithmods.BWMod.init(BWMod.java:58) ~[BWMod.class:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]

at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]

at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]

at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]

at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]

at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744) ~[Loader.class:?]

at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) ~[FMLServerHandler.class:?]

at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) ~[FMLCommonHandler.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]

Caused by: java.lang.IllegalAccessError: Class 'betterwithmods.module.tweaks.MineshaftGeneration' no access to: class 'net.minecraft.world.gen.structure.StructureMineshaftPieces$Peice'

at java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:1010) ~[?:1.8.0_192]

at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_192]

at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:843) ~[?:1.8.0_192]

at betterwithmods.module.tweaks.MineshaftGeneration.init(MineshaftGeneration.java:55) ~[MineshaftGeneration.class:?]

at betterwithmods.module.Module.lambda$init$3(Module.java:150) ~[Module.class:?]

at betterwithmods.module.Module$$Lambda$2546.00000000A7C8A450.accept(Unknown Source) ~[?:?]

at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_192]

at betterwithmods.module.Module.forEachEnabled(Module.java:212) ~[Module.class:?]

at betterwithmods.module.Module.init(Module.java:150) ~[Module.class:?]

at betterwithmods.module.ModuleLoader.lambda$init$3(ModuleLoader.java:80) ~[ModuleLoader.class:?]

at betterwithmods.module.ModuleLoader$$Lambda$2545.00000000A7C8A000.accept(Unknown Source) ~[?:?]

at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_192]

at betterwithmods.module.ModuleLoader.forEachEnabled(ModuleLoader.java:200) ~[ModuleLoader.class:?]

at betterwithmods.module.ModuleLoader.init(ModuleLoader.java:80) ~[ModuleLoader.class:?]

at betterwithmods.BWMod.init(BWMod.java:58) ~[BWMod.class:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]

at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]

at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]

at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]

at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]

at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744) ~[Loader.class:?]

at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) ~[FMLServerHandler.class:?]

at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) ~[FMLCommonHandler.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:813) ~[?:1.8.0_192]

Caused by: java.lang.IllegalAccessException: Class 'betterwithmods.module.tweaks.MineshaftGeneration' no access to: class 'net.minecraft.world.gen.structure.StructureMineshaftPieces$Peice'

at java.lang.invoke.MethodHandles$Lookup.checkClassAccess(MethodHandles.java:420) ~[?:1.8.0_192]

at java.lang.invoke.MethodHandles$Lookup.accessCheckArgRetTypes(MethodHandles.java:640) ~[?:1.8.0_192]

at java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:984) ~[?:1.8.0_192]

at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_192]

at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:843) ~[?:1.8.0_192]

at betterwithmods.module.tweaks.MineshaftGeneration.init(MineshaftGeneration.java:55) ~[MineshaftGeneration.class:?]

at betterwithmods.module.Module.lambda$init$3(Module.java:150) ~[Module.class:?]

at betterwithmods.module.Module$$Lambda$2546.00000000A7C8A450.accept(Unknown Source) ~[?:?]

at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_192]

at betterwithmods.module.Module.forEachEnabled(Module.java:212) ~[Module.class:?]

at betterwithmods.module.Module.init(Module.java:150) ~[Module.class:?]

at betterwithmods.module.ModuleLoader.lambda$init$3(ModuleLoader.java:80) ~[ModuleLoader.class:?]

at betterwithmods.module.ModuleLoader$$Lambda$2545.00000000A7C8A000.accept(Unknown Source) ~[?:?]

at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_192]

at betterwithmods.module.ModuleLoader.forEachEnabled(ModuleLoader.java:200) ~[ModuleLoader.class:?]

at betterwithmods.module.ModuleLoader.init(ModuleLoader.java:80) ~[ModuleLoader.class:?]

at betterwithmods.BWMod.init(BWMod.java:58) ~[BWMod.class:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]

at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]

at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]

at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) ~[forge-1.12.2-14.23.4.2707-universal.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]

at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]

at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]

at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744) ~[Loader.class:?]

at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) ~[FMLServerHandler.class:?]

at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) ~[FMLCommonHandler.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:813) ~[?:1.8.0_192]

[ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/gs-40716/./crash-reports/crash-2019-02-27_20.28.19-server.txt

[INFO] [net.minecraft.server.MinecraftServer]: Stopping server

[INFO] [net.minecraft.server.MinecraftServer]: Saving worlds

Exception in thread "Server thread" net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)

Caused by: java.lang.NullPointerException

at appeng.core.AppEng.serverStopped(AppEng.java:288)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)

at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

at com.google.common.eventbus.EventBus.post(EventBus.java:217)

at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)

at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

at com.google.common.eventbus.EventBus.post(EventBus.java:217)

at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)

at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:855)

at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:507)

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)

at java.lang.Thread.run(Thread.java:813)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
