### ISSUE TITLE
Game Crashed on Startup.

### ISSUE THREAD

**Issue by mixten64** [DarkPacks/SevTech-Ages#3721]
So I was trying to play Sevtech on the Twitch app on Windows 10 and when I boot up the game it kicks me out and says on the screen "an unexpected issue occurred and the game has crashed. We're sorry for the inconvenience" here's the logs

[09:51:12] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:51:12] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by sk2048** [comment]
That's really early in the loading process, before Forge has even properly prepared the environment. Nothing to do with SevTech is even being loaded. Delete the instance and try again.

**Comment by mixten64** [comment]
> That's really early in the loading process before Forge has even properly prepared the environment. Nothing to do with SevTech is even being loaded. Delete the instance and try again.

What do you mean?

**Comment by sk2048** [comment]
Sorry, Twitch calls them profiles. When you're in the list of Minecraft modpacks you have installed, right click SevTech Ages and click "Remove Profile"
