### ISSUE TITLE
Issue launching server on mxlinux

### ISSUE THREAD

**Issue by Froggg** [DarkPacks/SevTech-Ages#4027]
Fresh install of mx19, specifically for running servers off of, came with java installed but its the latest version so sure, extract .zip, run install.sh, change the min/max ram to amounts within my limit (16GB total, set max to 12, shouldn't be an issue on 64bit linux right?) then upon running ServerStart.sh, I receive this
`Starting SevTech Ages Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
`
doesn't even print a log cause this is just straight error in launching the jar I think? My apologies in case I missed something or misformatted this, correct me if I have, but I couldn't find any similar issues, or a better way to format. Thank you in advance, y'all have an awesome dev team

**Comment by sam-kirby** [comment]
> came with java installed but its the latest version

This is your issue. Minecraft Forge for 1.12.2 can only run on Java 8 due to changes in reflection changing how private class members are accessed.

Forge for 1.14+ will run on later Java versions as some future proofing has taken place, but last I checked this isn't officially supported as Minecraft itself still targets Java 8.
