### ISSUE TITLE
Crash Server when i go on the moon

### ISSUE THREAD

**Issue by hikinata** [DarkPacks/SevTech-Ages#4112]
## Bug Report
Hello,

The server crashes, and the client stays frozen when I leave for the moon.
I am stuck in loading, impossible to go to the moon with the rocket.
Once the game restart my character arrived on the moon outside of the rocket of course which disappeared.
And the advancement is not validated.

I tried several times, it crashes every time ..

## Possible Solution
The solution will be to pass the age with the orders, and to reload the world after the crash, but that means that with each new planet I risk having the problem

## Logs
[22:42:47] [Server thread/INFO] [journeymap]: dim-28 (Initialized) Setting config file to version "5.5.4": journeymap.server.dim-28.config
[22:42:47] [Server thread/INFO] [journeymap]: dim-28 (Valid) Creating config file: ./journeymap/server/5.5/journeymap.server.dim-28.config
[22:42:47] [Server thread/INFO] [Galacticraft]: Server attempting to transfer player vamf1 to dimension -28
[22:42:47] [Server thread/ERROR] [Galacticraft]: Error occurred when attempting to transfer entity to dimension: moon.moon
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: java.lang.IllegalStateException: Player changed world without us noticing. Did some third-party mod do something weird?
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.updateActiveViews(ServerWorldsManagerImpl.kt:67)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.management.PlayerChunkMap.handler$addPlayerWithViews$zbh000(SourceFile:549)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.management.PlayerChunkMap.func_72683_a(SourceFile)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.management.PlayerList.func_72375_a(PlayerList.java:290)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.teleportEntity(WorldUtil.java:854)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.transferEntityToDimension(WorldUtil.java:746)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.transferEntityToDimension(WorldUtil.java:716)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onServerTick(TickHandlerServer.java:280)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2225_TickHandlerServer_onServerTick_ServerTickEvent.invoke(.dynamic)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[22:42:47] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at java.lang.Thread.run(Thread.java:748)
[22:42:48] [Server thread/INFO] [Galacticraft]: Found matching world (-28) for name: moon.moon
[22:42:48] [Server thread/INFO] [journeymap]: Hikinata joining dimension -28
[22:42:48] [Server thread/INFO] [Galacticraft]: Server attempting to transfer player Hikinata to dimension -28
[22:42:48] [Server thread/ERROR] [Galacticraft]: Error occurred when attempting to transfer entity to dimension: moon.moon
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: java.lang.IllegalStateException: Player changed world without us noticing. Did some third-party mod do something weird?
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.updateActiveViews(ServerWorldsManagerImpl.kt:67)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.management.PlayerChunkMap.handler$addPlayerWithViews$zbh000(SourceFile:549)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.management.PlayerChunkMap.func_72683_a(SourceFile)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.management.PlayerList.func_72375_a(PlayerList.java:290)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.teleportEntity(WorldUtil.java:854)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.transferEntityToDimension(WorldUtil.java:746)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.util.WorldUtil.transferEntityToDimension(WorldUtil.java:716)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onServerTick(TickHandlerServer.java:280)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2225_TickHandlerServer_onServerTick_ServerTickEvent.invoke(.dynamic)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[22:42:48] [Server thread/INFO] [STDERR]: [micdoodle8.mods.galacticraft.core.tick.TickHandlerServer:onServerTick:294]: 	at java.lang.Thread.run(Thread.java:748)
[22:42:53] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_222]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.PlayerChunkMap.handler$updateMovingPlayerWithViews$zbh000(SourceFile:602) ~[ou.class:?]
	at net.minecraft.server.management.PlayerChunkMap.updateMovingPlayer(SourceFile) ~[ou.class:?]
	at net.minecraft.server.management.PlayerList.serverUpdateMovingPlayer(PlayerList.java:383) ~[pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:584) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayer.processPacket(SourceFile:126) ~[lk.class:?]
	at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.processPacket(SourceFile:18) ~[lk$b.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
[22:43:02] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: vamf1 lost connection: Timed out
[22:43:02] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: vamf1 left the game
[22:43:02] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.server.management.PlayerChunkMap.handler$removePlayerWithViews$zbh000(SourceFile:569) ~[ou.class:?]
	at net.minecraft.server.management.PlayerChunkMap.removePlayer(SourceFile) ~[ou.class:?]
	at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:414) ~[pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:853) ~[pa.class:?]
	at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:453) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:213) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[22:43:02] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/darknat/Modpack/./crash-reports/crash-2020-05-08_22.43.02-server.txt
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[22:43:02] [Server thread/WARN] [net.minecraft.network.NetworkManager]: handleDisconnection() called twice
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/the_nether
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/Storage Cell
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.asteroids
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.Ceres
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.Eris
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.Jupiter
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.kepler22b
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.mars
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.Mercury
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.Neptune
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.Pluto
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.Saturn
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.Uranus
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/planet.venus
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.callisto
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.deimos
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.europa
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.ganymede
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.iapetus
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.io
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.moon
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.oberon
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.phobos
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.rhea
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.titan
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.titania
[22:43:02] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/moon.triton
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension 0
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension 2
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -30
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -20
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -21
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -15
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -22
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -29
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -13
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -18
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -19
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -16
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -17
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -31
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1505
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1503
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1501
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1506
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1511
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1500
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -28
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1509
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1502
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1507
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1508
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1510
[22:43:02] [Server thread/INFO] [FML]: Unloading dimension -1504
[22:43:02] [Server thread/INFO] [Actually Additions]: Unloaded WorldData!
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -30
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -20
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -21
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -15
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -22
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -29
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -13
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -18
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -19
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -16
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -17
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -31
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1505
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1503
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1501
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1506
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1511
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1500
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1509
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1502
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1507
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1508
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1510
[22:43:03] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1504
[22:43:03] [Server thread/INFO] [mcjtylib_ng]: Cleaning up all world data: 2 data blobs
[22:43:03] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[22:43:03] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
* Crash Log:

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2020-05-08 22:43:02 CEST
Description: Exception in server tick loop

java.lang.NullPointerException
    at net.minecraft.server.management.PlayerChunkMap.handler$removePlayerWithViews$zbh000(SourceFile:569)
    at net.minecraft.server.management.PlayerChunkMap.removePlayer(SourceFile)
    at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:414)
    at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:853)
    at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:453)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:213)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748) 

## Client Information

* Modpack Version: 3.1.2 hotfix 1
* Java Version: 8
* Launcher Used:Twitch
* Memory Allocated:
* Server/LAN/Single Player:Server
* Optifine Installed:Yes
* Shaders Enabled:no

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version: 8
* Operating System: Ubuntu
* Hoster/Hosting Solution: One provider 
* Sponge (Non-Vanilla Forge) Server:

**Comment by hikinata** [comment]
Hi, sorry i have found the problem, i have add "better portal mod" and it's him that do bug the server :/ you can close this tickets
