### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by Neverless90** [DarkPacks/SevTech-Ages#4327]
## Bug Description

 Crash on loading of Minecraft

### Did this behavior use to work in the previous version?

 Dunno, this is my first try to download your mod pack

## Steps to Reproduce (for bugs)

 Started the game and crashed after initializing, On my 4th try I only got the Mojang Logo, then a black screen, then a crash. My earlier tries have seemingly just installed all the mods.
1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:
I'm new to this, so I got no idea how to use PasteBin, nor do I know Gist. Minecraft gives the error: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Exit Code: -1

## Client Information
* Modpack Version: Version 3.1.7
* Java Version: taskmanager gives Java(TM) Platform SE binary, otherwise it is an automatic version
* Launcher Used: Twitch to install the mod, then press play and logged in on the Minecraft Launcher
* Memory Allocated: Task manager read about 4.000mB before a forced quit
* Server/LAN/Single Player: Single Player
* Optifine Installed: If it is included in your pack than yes, otherwise No
* Shaders Enabled: Same as above

## World Information
* Modpack Version world created in: Not Applicable
* Additional Content Installed: Nothing 

__________________________________________________________________________________
This is probably helpful

Time: 10/4/20 11:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at mod.chiselsandbits.items.ItemChiseledBit.getBitStateName(ItemChiseledBit.java:156)
	at mod.chiselsandbits.items.ItemChiseledBit.getBitTypeName(ItemChiseledBit.java:208)
	at mod.chiselsandbits.items.ItemChiseledBit.func_77653_i(ItemChiseledBit.java:215)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at de.ellpeck.actuallyadditions.mod.event.ClientEvents.onTooltipEvent(ClientEvents.java:90)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2442_ClientEvents_onTooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:42)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:23)
	at mezz.jei.ingredients.IngredientInformation.getTooltipStrings(IngredientInformation.java:35)
	at mezz.jei.ingredients.IngredientListElement.getTooltipStrings(IngredientListElement.java:123)
	at mezz.jei.ingredients.IngredientFilter$$Lambda$5879/299434562.getStrings(Unknown Source)
	at mezz.jei.ingredients.IngredientFilter.addIngredient(IngredientFilter.java:117)
	at mezz.jei.ingredients.IngredientFilter.addIngredients(IngredientFilter.java:103)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:86)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

If you need more info or if I'm dumb than please message me back. I really want to try your mod pack!

**Comment by SkeLLiwag** [comment]
mine does this 2 dont understand what it means tried multiple re installs

**Comment by sam-kirby** [comment]
The game needs more memory - try with 6-8GB
