### ISSUE TITLE
Constantly Getting Disconnected Despite All Fix Attempts

### ISSUE THREAD

**Issue by MinhKyng** [DarkPacks/SevTech-Ages#4359]
## Bug Description

 I am having problems staying connected to a friend's server hosted on server.pro
I get disconnected from the server over a random interval of time between 2.5 mins to 20 mins. Sometimes I can stay on for several hours, sometimes I can barely stay on. I've tried every fix that pops up in google and none of them work. I'm the only one who seems to have this issue, no one else. I'm getting really frustrated because I've tried basically everything that shows up in google.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:
[18:08:20] [Netty Client IO #3/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_271]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_271]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_271]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_271]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_271]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

## Client Information
* Modpack Version: 3.1.7
* Java Version:1.8.0_271
* Launcher Used: MultiMC and Twitch
* Memory Allocated: 7424 MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.7
* Additional Content Installed: None.

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution: server.pro
* Sponge (Non-Vanilla Forge) Server:

**Comment by MinhKyng** [comment]
List of solutions:
I've tried disabling my firewall on ethernet and on wireless connection.
I've reinstalled the lastest version of java 1.8 3 times
I've tried running "netsh winsock reset" and netsh interface ipv4 set subinterface "local area connection" mtu=750 store=persistent" in the command prompt\
I've downloaded the config folder from the server and replaced my files with those
I've donwloaded the mods folder from the server and replaced my files with those

**Comment by MinhKyng** [comment]
It was an issue with server.pro, nothing to do with my system.

**Comment by SolarusRex** [comment]
what was the issue with teh server? im getting the same error on my friends server
