### ISSUE TITLE
Astral Sorcery block interaction causes world crash.

### ISSUE THREAD

**Issue by CPatton77** [DarkPacks/SevTech-Ages#4425]
## Bug Description

I was just working on progression with Astral Sorcery and eventually made the Lens block. I placed it on top of the Starlight Crafting Altar (2nd Tier table) just to place it and it ended up crashing my server.

I don't have anything else other than place a Lens block on top of a Starlight Crafting Altar

Additionally, I've removed BetterFoliage and FancyBlockparticles for performance but I don't really think that'd matter in this case.

### Did this behavior use to work in the previous version?

I've never played anything other than 3.1.7

## Steps to Reproduce (for bugs)

Place an AS Lens on top of an AS Starlight Crafting Altar

I've also recreated it in SP with no results at all.

## Logs

* Client/Server Log: 
* Crash Log: https://pastebin.com/vri06Fvg

## Client Information
* Modpack Version: 3.1.7
* Java Version: 1.8.0_261
* Launcher Used: Twitch/CurseForge
* Memory Allocated: 4 GB
* Server/LAN/Single Player: Server
* Optifine Installed: Nope
* Shaders Enabled: Nope

## World Information
* Modpack Version world created in: 3.1.7
* Additional Content Installed: Nope

## Server Information
* Java Version: 1.8.0_261
* Operating System: Windows 10 64-bit
* Hoster/Hosting Solution: Personally ran server
* Sponge (Non-Vanilla Forge) Server:

**Comment by CPatton77** [comment]
I was expecting the chunk to be corrupt upon loading into the server again but surprisingly it isn't. I was able to break the two blocks in question and the server is throwing errors for the Lens only like it has been. After breaking the block it turned into one of those phantom blocks where nothing's there but not really.

**Comment by CPatton77** [comment]
Every 45 seconds it's throwing this error now

[11:53:00] [Server thread/ERROR] [FML]: A TileEntity type hellfirepvp.astralsorcery.common.tile.network.TileCrystalLens has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException: null
        at hellfirepvp.astralsorcery.common.tile.network.TileCrystalLens.writeCustomNBT(TileCrystalLens.java:228) ~[TileCrystalLens.class:?]
        at hellfirepvp.astralsorcery.common.tile.base.TileEntitySynchronized.func_189515_b(TileEntitySynchronized.java:47) ~[TileEntitySynchronized.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:383) [aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:174) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

I've filled the block in and it went away fine, Spawned in a new one and just placed it on the floor, crashed again.

**Comment by dave-mccloskey** [comment]
I dupe all the same behavior BigWaifu reports
