### ISSUE TITLE
Server start.bat issue

### ISSUE THREAD

**Issue by Iluvsevtech** [DarkPacks/SevTech-Ages#4509]
When ever i run server start.bat it  says a paragraph: 
Starting SevTech Ages Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more
Press any key to continue . . .

 after I press any key it crashes crashes and it doesnt create the eula text file i need, I have java 8, jarfix, forge and it still doesn't work, Please reply because I love sevtech and I would like to play it with my friends

**Comment by sam-kirby** [comment]
You are missing the log4j library. This is part of the vanilla Minecraft jar.

Try running the installation step again. If this doesn't help, seek support on Discord - https://discord.gg/darkosto

You do not need jarfix to run a server.
