### ISSUE TITLE
Issue when starting server

### ISSUE THREAD

**Issue by Shin69x** [DarkPacks/SevTech-Ages#4575]
## Bug Description

When I try to start the server I get this error message on the console:

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

## Logs

* Client/Server Log: Could not find any
* Crash Log: Could not find any

## Client Information
* Modpack Version:<1.12.2>
* Java Version:<8 Update 291>
* Launcher Used:<Curseforge>
* Memory Allocated:<8GB>
* Server/LAN/Single Player:<Server>
* Optifine Installed:<No>
* Shaders Enabled:<No>

## World Information
* Modpack Version world created in:<3.2.1>
* Additional Content Installed:<None>

## Server Information
* Java Version:<8 Update 291>
* Operating System:<Windows 10 (1909)>
* Hoster/Hosting Solution: From Home PC
* Sponge (Non-Vanilla Forge) Server:<No>

**Comment by sam-kirby** [comment]
You must use Java 8 when playing modded 1.12.2 due to changes in later versions of Java being incompatible with Forge.

You will want to install a 64-bit version of Java 8 to be able to allocate enough memory for the server to operate.
