### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by Ferryj10** [DarkPacks/SevTech-Ages#4601]
## Bug Description

 When trying to launch the server from the downloaded server files off of curseforge and following the instructions in the README.txt file the server doesn't start providing the error 

Starting SevTech Ages Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Press any key to continue . . .

### Did this behavior use to work in the previous version?

 I have not tried creating a server like this before.

## Steps to Reproduce (for bugs)

not sure what has caused the error, cant reproduce. 
1.
2.
3.

## Logs

* Client/Server Log: NA
* Crash Log:  
* Starting SevTech Ages Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Press any key to continue . . .

## Client Information
* Modpack Version:SevTech-Ages_3.2.1.zip
* Java Version:java version "16.0.1" 2021-04-20
* Launcher Used: curseforge
* Memory Allocated:4gb
* Server/LAN/Single Player: attempted server wont start)
* Optifine Installed: no 
* Shaders Enabled: no 

## World Information
* Modpack Version world created in: NA
* Additional Content Installed: NA
 

## Server Information
* Java Version: java version "16.0.1" 2021-04-20
* Operating System: Windows 10 64-bit
* Hoster/Hosting Solution: 
* Sponge (Non-Vanilla Forge) Server:NA

**Comment by sam-kirby** [comment]
You must use Java 8 with Forge for 1.12.2 - there is no way you are using Java 16 with your client.
