### ISSUE TITLE
Following the steps in README but still not working.

### ISSUE THREAD

**Issue by TrevorB13** [DarkPacks/SevTech-Ages#4630]
I have followed every line in order and am able to setup all other kinds of server. I got this server pack from forge and this is what I get every time. Thanks in advance! 

Starting SevTech Ages of the Sky Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Press any key to continue . . .

**Comment by sam-kirby** [comment]
You must use Java 8. Forge for 1.12.2 is incompatible with later versions of Java.

If you need further help, please use the Discord server - https://discord.gg/darkosto
