### ISSUE TITLE
Joining a vanilla server shows no blocks. (HUB Server/Bungeecord)

### ISSUE THREAD

**Issue by Zilacon** [DarkPacks/SevTech-Ages#4696]
## Bug Description
Many networks use bungeecord to send players to the HUB when a server goes down, or to join the HUB to join multiple modpack servers. These HUB's are always vanilla servers, usually with plugins like viaversion and protocolsupport (does not apply here, issue happens on a pure vanilla server with zero plugins).

When joining a vanilla server, no matter what software its running on, everything is invisible. No blocks load or appear, but you can clearly walk around and interact with the blocks. You just cant see anything.

This issue is caused by the mod NotEnoughID's. Its original version created by Fewizz had a very similar issue with its 1.7.10 version of the mod. Fewizz worked with us to solve these issues a long time ago. But it seems like a new variant of the problem has re-appeared in the newer continuation of his mod.

### Did this behavior use to work in the previous version?
No, this is broken on all versions.

## Steps to Reproduce (for bugs)
Launch the pack, join a vanilla server.

## Logs
This is the only error we get when joining the server from the client:  
[15:40:44] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_332]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_332]
    at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
    at net.minecraft.world.chunk.Chunk.setIntBiomeArray(Chunk.java:1661) ~[axw.class:?]
    at net.minecraft.world.chunk.Chunk.redirect$zzj000$readBiomeByteArray(Chunk.java:2136) ~[axw.class:?]
    at net.minecraft.world.chunk.Chunk.func_186033_a(Chunk.java:1182) ~[axw.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[brz.class:?]
    at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[je.class:?]
    at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[je.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
    ... 17 more

## Client Information
* Modpack Version: 2.3.2
* Java Version: Java 8
* Launcher Used: Curse
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 2.3.2
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
The pack uses a modified protocol to get around the block ID limits imposed by vanilla Minecraft 1.12.2 - it therefore does not understand a vanilla server. If you absolutely need this functionality, try version 3.0.8 - this was the last release where we were under the block ID limit.

This will not be resolved.

**Comment by Zilacon** [comment]
> 

As ive stated in this post, we had this issue with the original 1.7.10 version of the mod before. And IT WAS fixed by the original mod developer/creator Fewizz.
This is not a matter of you resolving, its a matter of reporting it to the mod team and updating the modpack with the fixed version.

**Comment by sam-kirby** [comment]
You are welcome to ask the developers of JEID for this feature; it is unnecessary for this modpack and so we will not be getting involved. It has been rejected in the past however:

https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/70#issuecomment-506095359

**Comment by Zilacon** [comment]
@sam-kirby Just wanted to let you know JustEnoughID's version 1.0.3-55 does not have this issue.
Just found this out by playing Roguelike Adventures & Dungeons as it hasn't been updated since december.
No issues joining my HUB.

**Comment by sam-kirby** [comment]
We already use 1.0.3-55 in v3.2.3 of SevTech though?

**Comment by Zilacon** [comment]
Hmm, the mystery thickens...
