### ISSUE TITLE
Can't get server to run

### ISSUE THREAD

**Issue by OneAndOnly0716** [DarkPacks/SevTech-Ages#4699]
## Bug Description

 Whenever I attempt to run the server using the ServerStart file, I get an error saying the server can't start. Sorry if I don't have all the information, I'm not sure where to find all of it. 

### Did this behavior use to work in the previous version?

  I've never attempted this game before. 

## Steps to Reproduce (for bugs)

1. Followed instructions given in README to set up server
2.Click ServerStart.batch
3. 

## Logs

* Client/Server Log:
* Crash Log:
Starting SevTech Ages Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Press any key to continue . . .

## Client Information
* Modpack Version: 3.4.3
* Java Version:1.12.2
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player: Server
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

## Server Information
* Java Version: 1.12.2
* Operating System: Windows
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
You must use Java 8; this is a limitation of Forge for 1.12.2.

If you need help getting this working, please ask on Discord (https://discord.gg/darkosto)
