### ISSUE TITLE
Crash upon Loading (raft mod?)

### ISSUE THREAD

**Issue by Eauledoit11** [DarkPacks/SevTech-Ages#4702]
## Bug Description

 I load into the game and after a second or two it crashes making the modpack unplayable by me. This issue has also been reported in #1726 which had a few solutions I tried, but none have worked, and more recently in #4470 that hasn't had any solutions. The server people have tried to alter the chunks on their end, I've tried to use the server console to replace the block with something else, I have reinstalled the modpack on the server and on my computer and nothing else has worked. My friend on the server can still run without issue, but I cannot.  

### Did this behavior use to work in the previous version?

I don't know if there was a version update, but I wasn't having this problem two weeks ago.

## Steps to Reproduce (for bugs)

As mentioned by a similar post, the issue seems to be with JustARaftMod having a float integer or some such.
1. I load the modpack.
2. I connect to the server.
3. A zombie growls and I crash.

## Logs

* Client/Server Log: https://pastebin.com/33QuS0VL
* Crash Log: https://pastebin.com/gBpKEeWe

## Client Information
* Modpack Version:3.2.3
* Java Version:1.12.2
* Launcher Used:CurseForge
* Memory Allocated:~7GB
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:forge-14.23.5.2860
* Additional Content Installed:none.

## Server Information
* Java Version:8
* Operating System:Windows X
* Hoster/Hosting Solution:BisectHosting
* Sponge (Non-Vanilla Forge) Server:
![crashCapture040822](https://user-images.githubusercontent.com/103231127/162489400-ed067430-9da5-4838-b9e1-30fc51740b09.PNG)

![reeCapture](https://user-images.githubusercontent.com/103231127/162490443-dbfc68f5-c002-4d01-b2b4-19c3527cc1cb.PNG)

**Comment by Candunc** [comment]
~~I've had a similar issue occur with the Immersive Petroleum motorboat - the crash occurred while I was trying to drive the boat, but does not occur simply with the boat in the water.~~

Seems to be related specifically to the raft, upon crashing again:

```
Time: 5/26/22 1:39 PM
Description: Rendering entity in world

java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at com.Mrbysco.JustARaftMod.entity.EntityRaft.func_70268_h(EntityRaft.java:1005)
	at com.Mrbysco.JustARaftMod.render.RenderRaft.setupRotation(RenderRaft.java:60)
	at com.Mrbysco.JustARaftMod.render.RenderRaft.doRender(RenderRaft.java:36)
	at com.Mrbysco.JustARaftMod.render.RenderRaft.func_76986_a(RenderRaft.java:14)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.Mrbysco.JustARaftMod.entity.EntityRaft.func_70268_h(EntityRaft.java:1005)
	at com.Mrbysco.JustARaftMod.render.RenderRaft.setupRotation(RenderRaft.java:60)
	at com.Mrbysco.JustARaftMod.render.RenderRaft.doRender(RenderRaft.java:36)
	at com.Mrbysco.JustARaftMod.render.RenderRaft.func_76986_a(RenderRaft.java:14)

-- Entity being rendered --
Details:
	Entity Type: jarm:raft (com.Mrbysco.JustARaftMod.entity.EntityRaft)
	Entity ID: 343190
	Entity Name: Raft
	Entity's Exact location: -190.00, 62.69, -658.64
	Entity's Block location: World: (-190,62,-659), Chunk: (at 2,3,13 in -12,-42; contains blocks -192,0,-672 to -177,255,-657), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.Mrbysco.JustARaftMod.render.RenderRaft@500d1b3b
	Location: 22.59,-8.42,-77.63 - World: (22,-9,-78), Chunk: (at 6,-1,2 in 1,-5; contains blocks 16,0,-80 to 31,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 15.7754545
	Delta: 0.28045252
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

[...]

Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

```
