### ISSUE TITLE
modpack won't load due to java?

### ISSUE THREAD

**Issue by blakjak08** [DarkPacks/SevTech-Ages#4712]
## Bug Description

<Not a technical person, but i tried to play this modpack and the crash log says it's a java issue. Tried changing the version of java, but nothing seemed to work>

### Did this behavior use to work in the previous version?

<I started playing in 3.2.1, but never finished >

## Steps to Reproduce (for bugs)

1. I'm using MultiMC as a launcher
2.
3.

## Logs

* Client/Server Log:
* Crash Log:<Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more>

## Client Information
* Modpack Version:<3.2.3>
* Java Version:<1.8.0_991, 17.0.2, 18, 18.0.1.1   nothing worked>
* Launcher Used:<MultiMC>
* Memory Allocated:<12G>
* Server/LAN/Single Player:<Single Player>
* Optifine Installed:<No>
* Shaders Enabled:<No>

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
You must use Java 8 - all newer versions are incompatible with Forge for 1.12.2 will not start due to the changed reflection model in Java 9+. Java 8 cannot possibly have this exact issue as it has no concept of modules - you'll note that modules are mentioned in the `Caused by:` line.

Please try with Java 8 and share the log from that version if you continue to have issues. MultiMC's full log would be best as it prints a fair amount of useful information before the game starts.

**Comment by Khezama** [comment]
Did you find a solution I have the same problem

**Comment by sam-kirby** [comment]
The solution is to use Java 8.

**Comment by Khezama** [comment]
But I'm in java 8 ....

nvm It worked thank you

**Comment by sam-kirby** [comment]
It is impossible for you to receive the error described in this issue whilst using Java 8.

It would be best if you either post your own issue fully describing your setup and the error you are encountering, or you talk to us on Discord at https://discord.gg/darkosto
