### ISSUE TITLE
Server don't start 

### ISSUE THREAD

**Issue by Nolito1** [DarkPacks/SevTech-Ages#4767]
## Bug Description

<A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more

### Did this behavior use to work in the previous version?

* Client/Server Log:<[19:14:55] [Server thread/INFO]: Starting minecraft server version 1.12.2
[19:14:55] [Server thread/INFO]: Loading properties
[19:14:55] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: Controlador no válido
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:276) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:282) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:176) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:329) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:396) ~[?:?]
	at nz$2.run(SourceFile:100) [minecraft_server.1.12.2.jar:?]
[19:14:55] [Server thread/INFO]: Default game type: SURVIVAL
[19:14:55] [Server thread/INFO]: Generating keypair
[19:14:56] [Server thread/INFO]: Starting Minecraft server on *:25565
[19:14:56] [Server thread/INFO]: Using default channel type
[19:14:56] [Server thread/INFO]: Preparing level "world"
[19:14:56] [Server thread/INFO]: Loaded 488 advancements
[19:14:56] [Server thread/INFO]: Preparing start region for level 0
[19:14:57] [Server thread/INFO]: Preparing spawn area: 45%
[19:14:58] [Server thread/INFO]: Preparing spawn area: 52%
[19:14:59] [Server thread/INFO]: Preparing spawn area: 67%
[19:15:00] [Server thread/INFO]: Preparing spawn area: 84%
[19:15:01] [Server thread/INFO]: Done (5,309s)! For help, type "help" or "?"
[19:15:02] [Server thread/INFO]: Stopping server
[19:15:02] [Server thread/INFO]: Saving players
[19:15:02] [Server thread/INFO]: Saving worlds
[19:15:02] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[19:15:03] [Server Shutdown Thread/INFO]: Stopping server
>

## Client Information
* Modpack Version:<!3.2.3>
* Java Version:<8>
* Launcher Used:<N/A>
* Memory Allocated:<4 GB>
* Server/LAN/Single Player:<Server>
* Optifine Installed:<No>
* Shaders Enabled:<No>

## World Information
* Modpack Version world created in:<3.2.3>
* Additional Content Installed:<No>

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
You seem to have attached two different logs; in the first you're using an unsupported version of Java. You must use Java 8 with forge for 1.12.2.

In the second log, you're launching a vanilla server, probably as you've double clicked minecraft_server.1.12.2.jar instead of the start script.

You should remove the world folder and ensure Java 8 (64-bit) is installed and set as your default before running the start script again.

If you cannot make Java 8 your default for whatever reason you can modify the start script to force the use of Java 8 by using its absolute path.

For more support please ask on Discord at https://discord.gg/darkosto
