### ISSUE TITLE
CME in Age 4 or 5

### ISSUE THREAD

**Issue by sam-kirby** [DarkPacks/SevTech-Ages#4841]
CME during world loading -> adding TEs to world:

```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
    at net.minecraft.world.World.addTileEntities(World.java:1949)
    at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:856)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:728)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
```

```
[09:35:23] [Server thread/INFO] [TES]: ##############################
[09:35:23] [Server thread/INFO] [TES]: Adding tile to world: immersivepetroleum:distillationtower
[09:35:23] [Server thread/INFO] [TES]: Position: BlockPos{x=-433, y=74, z=1741}, Dimension: 0
[09:35:23] [Server thread/INFO] [TES]: #############DONE#############
[09:35:23] [Server thread/INFO] [TES]: ##############################
[09:35:23] [Server thread/INFO] [TES]: Adding tile to world: mekanism:mechanical_pipe
[09:35:23] [Server thread/INFO] [TES]: Position: BlockPos{x=-435, y=70, z=1739}, Dimension: 0
[09:35:23] [Server thread/INFO] [TES]: #############DONE#############
[09:35:23] [Server thread/INFO] [TES]: ##############################
[09:35:23] [Server thread/INFO] [TES]: Adding tile to world: mekanism:mechanical_pipe
[09:35:23] [Server thread/INFO] [TES]: Position: BlockPos{x=-433, y=70, z=1739}, Dimension: 0
[09:35:23] [Server thread/INFO] [TES]: #############DONE#############
[09:35:23] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
```
The last TE to be successfully loaded is a mechanical pipe from Mekanism. This is (x: -432 -> -433) on a chunk boundary - important?

Iterator invalidation during adding TE?
Looking for anything that touches Chunk.tileEntities during loading.

**Comment by sam-kirby** [comment]
More diagnostics

```
[10:51:36] [Server thread/INFO] [TES]: ##############################
[10:51:36] [Server thread/INFO] [TES]: Adding tile to world: mekanism:mechanical_pipe
[10:51:36] [Server thread/INFO] [TES]: Position: BlockPos{x=-433, y=70, z=1739}, Dimension: 0
[10:51:36] [Server thread/INFO] [sevpatches]: Entry added
tv.darkosto.sevpatches.ShoutyHashmap.put(ShoutyHashmap.java:10)
  at net.minecraft.world.chunk.Chunk.addTileEntity(Chunk.java:836)
  at net.minecraft.world.World.setTileEntity(World.java:2462)
  at net.minecraft.world.chunk.Chunk.getTileEntity(Chunk.java:801)
  at net.minecraft.world.World.getTileEntity(World.java:2402)
  at mekanism.common.util.MekanismUtils.getTileEntity(MekanismUtils.java:1085)
  at mekanism.common.tile.transmitter.TileEntitySidedPipe.canConnectMutual(TileEntitySidedPipe.java:261)
  at mekanism.common.tile.transmitter.TileEntitySidedPipe.getPossibleTransmitterConnections(TileEntitySidedPipe.java:132)
  at mekanism.common.tile.transmitter.TileEntitySidedPipe.refreshConnections(TileEntitySidedPipe.java:368)
  at mekanism.common.tile.transmitter.TileEntitySidedPipe.recheckConnections(TileEntitySidedPipe.java:428)
  at mekanism.common.tile.transmitter.TileEntityTransmitter.recheckConnections(TileEntityTransmitter.java:133)
  at mekanism.common.tile.transmitter.TileEntitySidedPipe.refreshConnections(TileEntitySidedPipe.java:388)
  at mekanism.common.tile.transmitter.TileEntitySidedPipe.onLoad(TileEntitySidedPipe.java:489)
  at net.minecraft.world.World.addTileEntity(World.java:1924)
  at net.minecraft.world.World.addTileEntities(World.java:1951)
  at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:856)
  at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
  at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
  at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:728)
  at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
  at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526), java.lang.Thread.run(Thread.java:750)
[10:51:36] [Server thread/INFO] [sevpatches]: Attempting to add tile entity at: BlockPos{x=-433, y=70, z=1737}
[10:51:36] [Server thread/INFO] [sevpatches]: TE: QuantumStorage.tiles.trashcans.TileTrashcanFluid
[10:51:36] [Server thread/INFO] [TES]: #############DONE#############
```

**Comment by sam-kirby** [comment]
![2023-12-19_23 57 02](https://github.com/DarkPacks/SevTech-Ages/assets/23245543/d37ecb17-8c6a-4bc7-8273-769e67619af0)
