### ISSUE TITLE
server does not initialize after installation

### ISSUE THREAD

**Issue by TertianRhymez** [DarkPacks/SevTech-Ages#4863]
The first time I downloaded the server it worked but I had some issues and I had to unzip and install it again but now after doing it several times I get this same error every time I reinstall or unzip it again until I downloaded the server again

.5.2860]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:?]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1359) [ForgeHooks.class:14.23.5.2860]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1326) [ForgeHooks.class:14.23.5.2860]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]
[15:29:43] [Server thread/INFO] [triumph]: Loading Custom Advancements
[15:29:44] [Server thread/ERROR] [triumph]: Error found while building advancement triumph:stage3/viescraft. There is already a criteria named hasRock0. Renaming to 'hasRock0-duplicate'
[15:29:44] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 369 advancements
Spliced in METHOD: net.minecraft.world.chunk.BlockStateContainer.func_186018_a
[15:29:45] [Server thread/INFO] [twilightforest]: Loaded a world with the tfEnforcedProgression game rule not defined.  Defining it.
[15:29:45] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 0
[15:29:45] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 1 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 1
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 50 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 50
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 51 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 51
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 52 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 52
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 53 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 53
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 144 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [compactmachines3]: Loaded data for compact machine world: 0 spawn points, next machine id is 0, players with beds: 0
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 144
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 28885 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 28885
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 20 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 20
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 10 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 10
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 7 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 7
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension 2 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension 2
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@5ac53261)
[15:29:46] [Server thread/INFO] [Astral Sorcery]: Checking GatewayCache integrity for dimension -1
[15:29:46] [Server thread/INFO] [Astral Sorcery]: GatewayCache checked and fully loaded in 0ms! Collected and checked 0 gateway nodes!
[15:29:46] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for level 0
[15:29:47] [Server thread/INFO] [net.minecraft]: [streams] River at tp 23 71 405
[15:29:47] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 4%
[15:29:48] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 8%
[15:29:49] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 15%
[15:29:50] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 23%
[15:29:51] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 33%
[15:29:52] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 44%
[15:29:53] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 56%
[15:29:54] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 62%
[15:29:55] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 73%
[15:29:56] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 86%
[15:29:57] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 97%
[15:29:58] [Server thread/INFO] [minecraft/DedicatedServer]: Done (17.843s)! For help, type "help" or "?"
[15:29:58] [Server thread/WARN] [enderutilities]: BlockUtils.getMatchingBlockStatesForString(): Invalid block state string 'bedrockbgone:better_bedrock'
[15:29:58] [Server thread/WARN] [enderutilities]: Invalid block state 'bedrockbgone:better_bedrock' in the energy bridge bedrock whitelist
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -30
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -20
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -21
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -15
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -22
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -29
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -13
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -18
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -19
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -16
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -17
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -31
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1505
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1503
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1501
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1506
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1511
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1500
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -28
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1509
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1502
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1507
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1508
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1510
[15:29:58] [Server thread/INFO] [Galacticraft]: Registered Dimension: -1504
[15:29:58] [Server thread/INFO] [NetherEx]: Setting up default biomes.
[15:29:58] [Server thread/INFO] [NetherEx]: Setting up custom biomes.
[15:29:58] [Server thread/INFO] [NetherEx]: Setting up default trades.
[15:29:58] [Server thread/INFO] [NetherEx]: Setting up custom trades.
[15:29:59] [Server thread/INFO] [Actually Additions]: No WorldData found, creating...
[15:29:59] [Server thread/INFO] [immersiveengineering]: WorldData loading
[15:29:59] [Server thread/INFO] [immersiveengineering]: WorldData not found
[15:29:59] [Server thread/INFO] [triumph]: Loading Custom Functions
[15:29:59] [Server thread/INFO] [minecraft/FunctionManager]: Loaded 13 custom command functions
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 1
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 50
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 51
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 52
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 53
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 144
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 28885
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 20
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 10
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension 7
[15:29:59] [Server thread/INFO] [FML]: Unloading dimension -1
[15:30:10] [BetterFps Update Checker/WARN] [BetterFps]: Could not check for updates: widget.mcf.li

**Comment by sam-kirby** [comment]
I'm not seeing an error here, the server log looks normal - `Unloaded dimension...` messages are typically the indicator that the server is ready to connect to.

**Comment by TertianRhymez** [comment]
> I'm not seeing an error here, the server log looks normal - `Unloaded dimension...` messages are typically the indicator that the server is ready to connect to.

but when I enter, it does not enter the server, it only says connecting and then it throws me off the server with an error, and the first time I start, I log in and everything is fine, it started when I started it for the second time and from there it always marks this even though it makes a blur and it flies away to create from 0 and it never lets me enter, but for now I found another way to play with friends without having to create this server by hosting my game on the lan and opening ports exactly the lan port that is opened on the lan to send it abroad and be able to play with friends, for now I'm going to leave it like this, but still thanks for the help
